name: "Init Project"
description: "Initializes a new project"

inputs:
  token:
    description: "GitHub Token"
    required: true
  repository:
    description: "GitHub repository name (e.g., Event-Based-Banking-Application/demo)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Make init.sh executable
      run: chmod +x "${{ github.action_path }}/init.sh"
      shell: bash

    - name: Run init.sh with derived values
      run: |
        REPO_NAME=$(basename "${{ inputs.repository }}")
        PACKAGE_NAME="org.arya.banking.${REPO_NAME//-/.}"
        MAIN_CLASS_NAME="$(echo "$REPO_NAME" | sed -E 's/(^|-)([a-z])/\U\2/g')"

        echo "📦 Derived repo: $REPO_NAME"
        echo "🔧 Package name: $PACKAGE_NAME"
        echo "🚀 Main class: $MAIN_CLASS_NAME"

        "${{ github.action_path }}/init.sh" "$REPO_NAME" "$PACKAGE_NAME" "$MAIN_CLASS_NAME"
      shell: bash

    - name: Setup Git and push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ inputs.token }}@github.com/${{ inputs.repository }}
        git add .
        git commit -m "chore: apply template initialization" || echo "No changes to commit"
        git push origin HEAD
      shell: bash
