name: "Init Project"
description: "Initializes a new project"

inputs:
  token:
    description: "GitHub Token"
    required: true
  repository:
    description: "GitHub repository name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ inputs.token }}@github.com/${{ inputs.repository }}
