name: "Init Project"
description: "Initializes repo after being created from a template"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run init script
      shell: bash  # ✅ required in composite actions
      run: |
        chmod +x ${{ github.action_path }}/init.sh
        ${{ github.action_path }}/init.sh "${{ github.repository }}"
